'use strict';

const { CrmDealAutomationRule, CrmActivity, CrmNotification, CrmInteraction, CrmCustomer } = require('../models');
const emailService = require('./emailService');
const { emitToTenant } = require('../socket');

const crmDealAutomationService = {
  
  async getRulesByStage(tenantId, stageId) {
    return await CrmDealAutomationRule.findAll({
      where: { tenant_id: tenantId, stage_id: stageId }
    });
  },

  async createRule(tenantId, stageId, data) {
    const { action_type, action_config } = data;
    
    if (!['create_task', 'send_email', 'notify_owner'].includes(action_type)) {
      throw new Error('Invalid action_type');
    }

    return await CrmDealAutomationRule.create({
      tenant_id: tenantId,
      stage_id: stageId,
      action_type,
      action_config: action_config || {},
      is_active: true
    });
  },

  async deleteRule(tenantId, ruleId) {
    const rule = await CrmDealAutomationRule.findOne({
      where: { id: ruleId, tenant_id: tenantId }
    });
    if (!rule) throw new Error('Rule not found');
    await rule.destroy();
    return true;
  },

  

  _parseTemplate(templateString, deal) {
    if (!templateString) return '';
    let parsed = templateString;
    const customerName = deal.customer?.name || 'Customer';
    const dealTitle = deal.title || 'Deal';
    const ownerName = deal.owner?.name || 'Owner';

    parsed = parsed.replace(/{{customer_name}}/g, customerName);
    parsed = parsed.replace(/{{deal_title}}/g, dealTitle);
    parsed = parsed.replace(/{{owner_name}}/g, ownerName);
    return parsed;
  },

  

  async triggerRules(deal, newStageId) {
    try {
      const rules = await this.getRulesByStage(deal.tenant_id, newStageId);
      if (!rules || rules.length === 0) return;

      console.log(`[Deal Automation] Found ${rules.length} rules for Deal ${deal.id} entering stage ${newStageId}`);

      for (const rule of rules) {
        if (!rule.is_active) continue;

        const config = typeof rule.action_config === 'string' ? JSON.parse(rule.action_config) : rule.action_config;

        switch (rule.action_type) {
          case 'create_task': {
            const taskTitle = this._parseTemplate(config.task_title || 'Follow up on deal', deal);
            const dueDays = config.due_in_days || 1;
            const dueAt = new Date();
            dueAt.setDate(dueAt.getDate() + dueDays);

            const activity = await CrmActivity.create({
              tenant_id: deal.tenant_id,
              related_type: 'deal',
              related_id: deal.id,
              activity_type: 'task',
              title: taskTitle,
              description: 'Auto-generated by Deal Automation Rule.',
              due_at: dueAt,
              owner_id: deal.owner_id || deal.created_by
            });
            emitToTenant(deal.tenant_id, 'activity:new', activity);
            break;
          }

          case 'notify_owner': {
            const message = this._parseTemplate(config.notification_message || 'Deal moved to new stage', deal);
            if (deal.owner_id) {
              const notification = await CrmNotification.create({
                tenant_id: deal.tenant_id,
                user_id: deal.owner_id,
                title: 'Deal Pipeline Update',
                body: message,
                type: 'info',
                link: `/crm/deals`
              });
              emitToTenant(deal.tenant_id, 'notification:new', notification);
            }
            break;
          }

          case 'send_email': {
            const customerId = deal.customer_id;
            if (!customerId) break;
            
            const customer = deal.customer || await CrmCustomer.findByPk(customerId);
            if (!customer || !customer.email) break;

            const subject = this._parseTemplate(config.email_subject || 'Update regarding your deal', deal);
            const body = this._parseTemplate(config.email_body || 'Your deal status has been updated.', deal);

            
            const emailSent = await emailService.sendMail({
              to: customer.email,
              subject,
              text: body
            });

            if (emailSent) {
              
              await CrmInteraction.create({
                tenant_id: deal.tenant_id,
                customer_id: customer.id,
                interaction_type: 'email',
                channel: 'email',
                direction: 'outbound',
                summary: `Auto-Email: ${subject}`,
                content: body,
                created_by: deal.owner_id || deal.created_by || 1
              });
            }
            break;
          }
        }
      }
    } catch (err) {
      console.error('[Deal Automation] Failed to trigger rules:', err);
    }
  }
};

module.exports = crmDealAutomationService;
